### PR TITLE
on ethics and values

### PR DESCRIPTION
**Pull request by mhagdorn**
just to get this started

### CODE REVIEW

**Comment by hvwaldow** [comment]
This section is generally feature complete in my mind. It has two parts: One slightly modified from @mhagdorn 's start, referring to general values as listed in the Software Engineering Code of Ethics [@Gotterbarn1999]. The other referring to specific ethical topics that should be common and specific for RSEs.

Pending issues here are:

+ There is room for a couple of references here and there. I just didn't get to do that yet.
+ It is not clear whether this is now too long in relation to other sections. Remedies are:
   1. Just shorten the individual points in the second part, or
   2. Distribute that content. Maybe the second part could go somewhere to teaching content.
 
I'd be happy to deal with that at a later stage in case the values thing goes in its +/- current shape into the next incarnation of main.

**Comment by CaptainSifff** [comment]
Great!
I quite like it. As feedback, I wonder why the words open or transparent are not used (I think) and I wonder whether the Data protection section should be reframed into data integrity.

**Comment by mhagdorn** [comment]
I agree, this is getting to the right place now. It occurred to me that maybe the ethics issues are also one of those things that make RSEs more like an academic than a software developer. Don't get me wrong, I do think that SEs also need to consider the moral stance on their work but their relationship to work is different. RSEs, like academics, have a lot more agency. Transparency and data integrity are very much part of the academic values. So maybe we could add that to the intro of the values section and refer to something that outlines the academic values.

**Comment by jngrad** [comment]
Excellent work! I find the text well written and well structured. The length seems about right to me.

**Comment by hvwaldow** [comment]
> I agree, this is getting to the right place now. It occurred to me that maybe the ethics issues are also one of those things that make RSEs more like an academic than a software developer. Don't get me wrong, I do think that SEs also need to consider the moral stance on their work but their relationship to work is different. RSEs, like academics, have a lot more agency. Transparency and data integrity are very much part of the academic values. So maybe we could add that to the intro of the values section and refer to something that outlines the academic values.

Good thought! I will give it a shot and try to integrate it.

**Comment by hvwaldow** [comment]
> Great! I quite like it. As feedback, I wonder why the words open or transparent are not used (I think) and I wonder whether the Data protection section should be reframed into data integrity.

+ "Open" and "transparent" certainly were in the values I wanted to transport. Will try to make that more explicit.

+ I think "data integrity" is a sub-category of the overarching "personal data" category (and adjacent to but different from "data protection"). Both also have meaning when no personal data is involved. But I am not sure whether data integrity **in general** should be under "Values". In any case I can amend that paragraph (Personal Data) with "data integrity", that is pretty important too and also prominent in GDPR.

**Pull request merged**
