### PR TITLE
RSE in NFDI and NFDI4Ing

### PR DESCRIPTION
**Pull request by braunms**
Prepared some text for NFDI4Ing and EduTrain. 

Still waiting for an answer if RSE is somehow specifically considered within EduTrain. In the section concept they explicitly refer to The Carpentries ([https://zenodo.org/record/6475541 ](https://zenodo.org/record/6475541), page 6, Aufgabenpaket 3)

@jlinx Please feel free to directly push changes to the branch...

### CODE REVIEW

**Comment by braunms** [comment]
The people I know related to NFDI couldn't tell me more specific details about RSE in EduTrain. Only that there are "many developments that have not yet been properly consolidated"...

**Comment by braunms** [comment]
[DALIA](https://www.fst.tu-darmstadt.de/forschung_fst/zusammenarbeit_in_der_forschung/dalia/dalia_ueberblick.en.jsp) ([GitLab](https://git.rwth-aachen.de/groups/dalia/-/epics/151)) is strongly connected to NFDI and its section EduTrain. 
Implements knowledge-base as semantically linked knowledge graph.
Any specific relation to RSE?

**Comment by CaptainSifff** [comment]
@braunms : there is an entire section in the NFDI working on RSE:
https://docs.google.com/document/d/1sfevW3Qbh8jcAwMRYkNTD8PstEy-MBqn2xbQH2ogYzU/edit#heading=h.w2secxckj3tq

since it's part of common infrastructures it's not yet that visible.

**Comment by braunms** [comment]
I actually asked Bernd Flemisch about RSE-related teaching materials within NFDI. But maybe because of my too specific question he haven't told me about other RSE developments :-P ...

**Pull request merged**
