### PR TITLE
CC-BY licensing of this repo

### PR DESCRIPTION
**Pull request by hvwaldow**

### CODE REVIEW

**Comment by CaptainSifff** [comment]
here's the CFF generator: https://citation-file-format.github.io/cff-initializer-javascript/#/

**Comment by CaptainSifff** [comment]
Now we also have a name: the teachingRSE project . We can also this in our license file.

**Comment by CaptainSifff** [comment]
Any updates over here?

**Review by MakisH — APPROVED** [review]
I think this is ready to merge as it is, no reason to try to integrate the CFF changes here. Let's just merge this and continue on the CFF in a separate PR.

**Comment by hvwaldow** [comment]
Re-checked and removed the CFF file which will be a separate PR addressing #253. I guess you can merge that now, @CaptainSifff.

**Pull request merged**
