### PR TITLE
Add section numbers

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
using https://github.com/tomduck/pandoc-xnos

### CODE REVIEW

**Comment by CaptainSifff** [comment]
looks cool!

**Comment by jpthiele** [comment]
Yes, very nice!

**Comment by CaptainSifff** [comment]
The numbering works, but I have issues with the table reference.
image

**Comment by CaptainSifff** [comment]
If we get this portable, we can merge this.

**Comment by BeastyBlacksmith** [comment]
But it is in the [compiled artifacts](https://github.com/CaptainSifff/paper_teaching-learning-RSE/suites/17870443398/artifacts/1025743519). Did you install the pandoc-xnos stuff locally? Or what is the difference between your system and CI?

**Comment by CaptainSifff** [comment]
Yes, I installed it locally. I would need to fix up the section lables next, and do not want to abuse the pipeline every time for that. This is arch linux. I'm using our makefile.

**Comment by jcohen02** [comment]
The section numbering in the paper summary at the end of the introduction was still hardcoded and was out of sync with the rest of the content (I think the "Values" section got added as Section 3?). I've therefore updated things to add tags to each of the headings and then to use these tag names in the paper summary so the numbering is automatically generated. I thought it was prefereable to be explicit with tag names by adding them manually, rather than relying on the default generated names that replace spaces with hyphens, etc.

On my system, I kept getting build errors telling me that hyperref needs to be loaded before cleveref and I had to add `- \usepackage{hyperref}` to the `header-includes` section in the YAML front-matter in the paper md files. However, I'm assuming this is not affecting the CI setup since things have been running successfully so I've not included this change.

Finally, I'm using pandoc 3 (which might also explain the above difference) and I hit the problem described in issue 28 in the [`pandoc-xnos` repo](https://github.com/tomduck/pandoc-xnos/issues) - updating the regex as suggested serves as a temporary fix - in case anyone else hits this issue.

**Comment by CaptainSifff** [comment]
Thank You @jcohen02

**Pull request merged**
