### PR TITLE
add a license file

### PR DESCRIPTION
**Pull request by CaptainSifff**
adds the CC-BY V4 license.

### CODE REVIEW

**Review by MakisH — APPROVED** [review]
Let's get approvals from all contributors, if possible, or at least some written confirmation in some form.

**Review by BeastyBlacksmith — APPROVED** [review]

**Review by braunms — APPROVED** [review]

**Review by mschwarzmeier — APPROVED** [review]

**Review by jpthiele — APPROVED** [review]

**Review by hvwaldow — APPROVED** [review]

**Review by juckel — APPROVED** [review]

**Review by braunms — APPROVED** [review]

**Review by unode — APPROVED** [review]

**Comment by jpthiele** [comment]
@HeidiSeibold @tobyhodges I couldn't find you under 'request review' but of course we need you to approve
adding the CC-BY license to the source files (the preprint on arXiv already has this license afaik).
Probably best if you just write a short comment about it.

**Comment by tobyhodges** [comment]
Absolutely okay with me 👍

**Review by dokempf — APPROVED** [review]

**Review by jngrad — APPROVED** [review]

**Comment by HeidiSeibold** [comment]
Sure I agree! (is that enough of a comment?)

**Comment by jcohen02** [comment]
This is fine with me, @jpthiele, however, shouldn't there be a copyright (or equivalent) line at the top which shows who people should provide attribution to? (On the basis that the intention of the CC-BY licence is to enable people to share/resuse/remix etc. content, but providing attribution to the original creator(s)).

I agree this is not entirely straightforward given the number of people involved but it could perhaps just say something like "(c) 2024 F. Goth and deRSE23 community contributors" ?

**Comment by CaptainSifff** [comment]
hmm, good idea... Wouldn't we usually include a CITATION.md file for that?

**Comment by jpthiele** [comment]
> This is fine with me, @jpthiele, however, shouldn't there be a copyright (or equivalent) line at the top which shows who people should provide attribution to? (On the basis that the intention of the CC-BY licence is to enable people to share/resuse/remix etc. content, but providing attribution to the original creator(s)).
> 
> I agree this is not entirely straightforward given the number of people involved but it could perhaps just say something like "(c) 2024 F. Goth and deRSE23 community contributors" ?

Good question. I agree that we should somehow shorten the description/name for the group of people. 
Maybe we do a short brainstorming tomorrow or at least a "think about it over the weekend" 

Funnily I was actually wondering the same thing for the beamer-tex source files of my git and RSE workshops for the institute.
But I couldn't find the 'Insert this comment block at the beginning' that is common in MIT and GPL licenses. 
If anyone knows anything we might add such a comment block in all Markdown files.

**Comment by CaptainSifff** [comment]
Missing @fer-rum , @juckel , @annalenalamprecht (although I'm pretty sure she agreed in a meeting) , @jlinx

**Comment by juckel** [comment]
I see myself listed under "changes approved" from the reviewer list for this PR

**Comment by annalenalamprecht** [comment]
Sure, I agree!

**Review by jcohen02 — APPROVED** [review]
This is fine with me - we discussed adding some form of copyright statement at the top of the LICENSE file (or a CITATION file) in today's meeting. This will help people who want to acknowledge this repository to know who to attribute it to.

**Comment by CaptainSifff** [comment]
Great progress! Now we only need to find @jlinx and @fer-rum

**Comment by CaptainSifff** [comment]
The reminder to @jlinx and @fer-rum

**Comment by CaptainSifff** [comment]
I received verbal acknowledgement by @jlinx  this evening.

**Comment by CaptainSifff** [comment]
@fer-rum If we don't receive a note somehow, that you are against CC-BY-V4 licensing till 20.02.24 , we take that to indicate you're fine with this change.

**Comment by CaptainSifff** [comment]
So, now we are CC-BY-V4.

**Pull request merged**
