### PR TITLE
Add Management to skill title, fixes #262

### LINKED ISSUE #262: Rephrase 'Communication' skill group to include management
The point was made that management is more than communication,
so it is not a good summary of the skills

### PR DESCRIPTION
**Pull request by jpthiele**

### CODE REVIEW

**Review by MakisH — APPROVED** [review]

**Comment by CaptainSifff** [comment]
If you go down that route, shouldn't you also specify what is managed?

**Comment by jpthiele** [comment]
> If you go down that route, shouldn't you also specify what is managed?

Don't we do that by the actual skills in the section?

**Comment by CaptainSifff** [comment]
Well, it's more like the title phrasing. Communication is manifestly human connotated. Management you can do of everything.

**Comment by jpthiele** [comment]
Which is why project management is not encompassed by communication alone, 
so the title does not fit fully. 
By placing it first and through the whole paper we put a good emphasis on the human factor I think.

**Pull request closed without merging**
