### PR TITLE
Consistently use sentence case in headings

### PR DESCRIPTION
**Pull request by MakisH**
Fixes a few inconsistencies.

I have not touched any capitalizations inside the text (e.g., "Machine Learning" vs "machine learning"), these are still inconsistently used. Should I enforce some variant of those as well?

Rendering:

Screenshot from 2023-11-15 09-55-31

### CODE REVIEW

**Comment by CaptainSifff** [comment]
I started out with Title Case, but since it's now consistent....

**Comment by CaptainSifff** [comment]
and machine learning should be lower case(personal opinion)

**Comment by jngrad** [comment]
Enforcing capitalization in the text would be easier with glossary, but then the Markdown rendering in GitHub would be even more unreadable. There is [hippwn/pandoc-glossaries](https://github.com/hippwn/pandoc-glossaries), but I'm not sure how compatible it is with our current pandoc pipeline.

**Review by jngrad — APPROVED** [review]

**Comment by MakisH** [comment]
> and machine learning should be lower case(personal opinion)

I will fix this in a separate PR, as the discussion on that, as there are probably going to be some discussions for some terms, and it is touching a large part of the text.

**Pull request merged**
