### PR TITLE
Added funder acknowledgement

### PR DESCRIPTION
**Pull request by jcohen02**

### CODE REVIEW

**Comment by jngrad** [comment]
This was briefly mentioned by @CaptainSifff in the last Zoom meeting. Everyone was invited to provide their funding information, if I recall correctly. Was the idea for everyone to push their commit here, and thus avoid a multitude of PRs and merge conflicts?

**Comment by jcohen02** [comment]
Ah, good point @jngrad, I was assuming this would just get merged and anyone else wanting to add acknowledgements could simply push an update with additional text.

However, maybe it makes more sense to leave this open, at least for a little while, and everyone can then add their acknowledgements into this PR and we can merge the updates as one block?

**Comment by jpthiele** [comment]
Yes, right. Maybe we should ping everybody and/or add a list for everyone to tick if they added acknowledgements (or don't need to)

**Review by knarrff — APPROVED** [review]
It is a little strange to see two unrelated commits in one merge request, but both look fine.

**Comment by jpthiele** [comment]
> It is a little strange to see two unrelated commits in one merge request, but both look fine.

I get that, but I thought it still related enough to not open a new PR when we talk about funding
and employment anyways. Especially, since we don't squash as far as I know.

**Comment by HeidiSeibold** [comment]
> **Acknowledgements**
> 
> Pinging all contributors - if you have acknowledgements you'd like to add, it would be great if you could push them to this PR (#77) and then update the table below. Many thanks. (...I hope I haven't missed anyone but my apologies if I have.)

None required from my end ✅

**Comment by mhagdorn** [comment]
> **Acknowledgements**
> 
> Pinging all contributors - if you have acknowledgements you'd like to add, it would be great if you could push them to this PR (#77) and then update the table below. Many thanks. (...I hope I haven't missed anyone but my apologies if I have.)
> 
also none required from me

**Pull request merged**
