### PR TITLE
Add a structured list of curricula

### LINKED ISSUE #97: Sort out and collect masters program.
We now have existing masters programs all over the place.( #69,  #4 )
We need to collect and structure them somehow.

### PR DESCRIPTION
**Pull request by MakisH**
Collects and sorts the programs listed in https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/4, as well as few more (and probably more will come during and after the review). This list is in a new file, and should eventually be moved to some webpage.

Closes #97.

Categories:

- Dedicated RSE curricula
- Curricula on Scientific Computing
- Curricula on Data Science
- Other initiatives

Besides the "other initiatives", everything is listed in a table, with the following information:

- Degree
- Name
- University
- Country
- Language

I have excluded domain-specific programs that happen to teach some RSE skills (too many) and CS-focused programs (well...).

Not sure who should review this, but cc @CaptainSifff and @jpthiele for the reviews and @knarrff as a reminder that we need some web page to publish this list eventually.

### CODE REVIEW

**Comment by CaptainSifff** [comment]
you've looked into #135 ?

**Comment by MakisH** [comment]
The spellchecker does not run because this new file is not listed in the files to check:

https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/ed36c7ce330d42bb9e9ab60ce563e1026afc019a/.github/workflows/spellcheck.yml#L33-L34

Since this list mainly has university names and is meant to be moved elsewhere, I am not sure if enabling the spellchecker is a good idea. We would need to add several exceptions.

**Comment by MakisH** [comment]
> you've looked into #135 ?

@CaptainSifff I looked at it, but I don't see any curricula or learning resources there. In the pad, I mostly see related work regarding skills, which are anyway partially mentioned in the Related Work section, and partially migrated into https://github.com/CaptainSifff/paper_teaching-learning-RSE/blob/main/related-work-training.md

**Comment by MakisH** [comment]
I was wrong regarding the spellcheck: It previously failed with a timeout. Triggering it again passed.

@jpthiele would maybe like to review this?

**Comment by MakisH** [comment]
@CaptainSifff I guess we can also just merge this already? Not urgent, but I like the feeling of closing boxes. :D

**Comment by CaptainSifff** [comment]
OK, you've probably volunteered into finding your favorite markdown static site generator....

**Pull request merged**
