### PR TITLE
266 critical thinking

### PR DESCRIPTION
**Pull request by mhagdorn**

### CODE REVIEW

**Comment by jpthiele** [comment]
The initial commit aligns with the goals we stated in #266 
especially in terms of a skill aspect for RSEs and relates to verification and validation of software
(which we should maybe state explicitly?)

The second commit however, reads not as a value we have but as a critique of society as it is currently.
So I don't feel it fits in the scope of a paper about teaching RSE skills and competencies.

**Comment by michelemartone** [comment]
Hi @jpthiele -- can you point out to any societal critique in that second commit? Please also see https://github.com/CaptainSifff/paper_teaching-learning-RSE/commit/b55efa6259c0c0c48f83110fc6fac63a806a641f#commitcomment-141301491 and the discussion in there.

**Comment by jpthiele** [comment]
The sentence about decision makers has a negative connotation of that being categorically wrong.

**Comment by michelemartone** [comment]
There is no statement that cost reducing is bad: that is neither stated, intended or implied.

But the decision makers in management position are often in that corner (the need to reduce costs), so it's a reality, which motivates automation and processes increasing productivity.
Without that we wouldn't be at this stage of prosperity, so if you want, is a very good thing that that pressure exist, as a side comment of me.

**Comment by mhagdorn** [comment]
I think the entire paragraph reads as a social critique because of its breadth. I don't have a problem with this particular direction of critique but I don't think it belongs into this paper. The way I see this paper is that we provide interested people with a starting point of what we consider to be fundamental to RSEs. Ethics, philosophy of science and epistemology are huge topics that we can't go into (we don't even satisfy the software engineers).

**Comment by michelemartone** [comment]
I agree this paragraph is framed pretty generally..

We started that we wanted to motivate the need for the RSE to have the ability (or skill?!) to assess when the result from the application of an advanced, reasoning like method (read: something like an "AI"-based assistant) is wrong.
Correct?

If and only if yes, how far is this paragraph from that?

**Comment by CaptainSifff** [comment]
closing in favour of #279 Discussion now continues over there.

**Pull request closed without merging**
