### PR TITLE
Started on chapter overview in intro

### PR DESCRIPTION
**Pull request by jpthiele**
I started to add an overview on the sections for the introduction. 
For the 'Organizational Infrastructures' I did not add anything yet as it was hard to combine the teachers aspect 
with the organizational aspects of acquiring RSE skills

### CODE REVIEW

**Comment by jpthiele** [comment]
Additionally I did not write anything on 'How do we reach people' and was instead wondering whether that might not be a 
better fit as a subsection of 'Challenges'?

**Comment by jpthiele** [comment]
FInal note @CaptainSifff as you are keeping track of TODOs 
During reading of the paper I noticed that some things were spelled in BE and some in AE so we should add a 
TODO for the final stages of the paper to unify that to one of those.

**Comment by CaptainSifff** [comment]
We now have #52 to remind us.

**Comment by CaptainSifff** [comment]
Since you had to look at the entire paper. Did you encounter anything peculiar?

**Comment by jpthiele** [comment]
Apart from the things mentioned here, no.

**Pull request merged**
