### PR TITLE
add maintenance and sustainability reason

### PR DESCRIPTION
**Pull request by mschwarzmeier**
Just adding the text from #105

### CODE REVIEW

**Comment by CaptainSifff** [comment]
I get why we should have this in the call to action. But I think we can be more constructive instead of declaring the funding situation to be difficult. maybe you could write the argument, that current DFG Project based funding does not align well with the timescales of RS and is often not available since the prerequisites don't match(research grants need to contain new things) anf BMBF funding is not available for a lot of software since direct applications are often a necessity. Therefore we can argue in the CTA that new funding lines have to be created for which Software projects can compete among themselves.

**Comment by CaptainSifff** [comment]
See #112

**Comment by tobyhodges** [comment]
It seems like what I am trying to say in #112 could be combined with what is being added here. Would you be happy for me to propose the changes from #112 into this branch, @mschwarzmeier?

Anything else that we could add on top of those two points?

**Comment by mschwarzmeier** [comment]
I transfered the content. I wuoldn't have seen a merge conflict upcoming but ok.
Closing this PR now.

**Comment by mschwarzmeier** [comment]
**To be continued in #112 !**

**Pull request closed without merging**
